# Site settings
title: TRAN QUOC THANG
description: TRAN QUOC THANG Resume

# User settings
username: TRAN QUOC THANG
user_description:
user_title: Senior Developer
email: thangquoctran.qb@gmail.com
# twitter_username: thangquoctran.qb
instagram_username: thangquoctran
facebook_username: thangquoctran.qb
linkedin_username: thangquoctran
github_username:  thangquoctranqb
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
